export const catalogProducts = [
  {
    id: 'prod-1',
    name: '哥斯大黎加 音樂家系列',
    category: '淺焙',
    profile: '杏桃 / 蜂蜜 / 花香',
    price: 750,
    roast: '淺焙',
    weight: '半磅',
    imageLabel: 'Costa Rica',
    tone: 'light',
  },
  {
    id: 'prod-2',
    name: '哥倫比亞 天堂莊園 聯盟花藝',
    category: '淺焙',
    profile: '紅石榴 / 葡萄 / 酒香',
    price: 800,
    roast: '淺焙',
    weight: '100G',
    imageLabel: 'Paradise',
    tone: 'warm',
  },
  {
    id: 'prod-3',
    name: '蜜香赤霞珠 聯盟花園莊園',
    category: '淺焙',
    profile: '花香 / 莓果 / 蜜甜',
    price: 900,
    roast: '淺焙',
    weight: '半磅',
    imageLabel: 'Muscat',
    tone: 'berry',
  },
  {
    id: 'prod-4',
    name: 'BeanSelf 經典精品人味',
    category: '中焙',
    profile: '堅果 / 奶油 / 可可',
    price: 500,
    roast: '中焙',
    weight: '半磅',
    imageLabel: 'Classic',
    tone: 'warm',
  },
  {
    id: 'prod-5',
    name: '肯亞 涅里高原 高海拔莊園',
    category: '淺焙',
    profile: '黑醋栗 / 柑橘 / 烏龍',
    price: 700,
    roast: '淺焙',
    weight: '半磅',
    imageLabel: 'Kenya',
    tone: 'light',
  },
  {
    id: 'prod-6',
    name: '哥斯大黎加 紅蜜處理',
    category: '淺焙',
    profile: '莓果 / 太妃糖 / 奶油',
    price: 750,
    roast: '淺焙',
    weight: '半磅',
    imageLabel: 'Red Honey',
    tone: 'warm',
  },
  {
    id: 'prod-7',
    name: '哥倫比亞 瑰夏花香微批',
    category: '淺焙',
    profile: '白花 / 柚香 / 茶感',
    price: 900,
    roast: '淺焙',
    weight: '100G',
    imageLabel: 'Geisha',
    tone: 'berry',
  },
  {
    id: 'prod-8',
    name: '衣索比亞 耶加雪菲',
    category: '淺焙',
    profile: '茉莉 / 佛手柑 / 檸檬',
    price: 650,
    roast: '淺焙',
    weight: '半磅',
    imageLabel: 'Yirgacheffe',
    tone: 'light',
  },
  {
    id: 'prod-9',
    name: '衣索比亞 谷吉 日曬花宴',
    category: '淺焙',
    profile: '莓果 / 杏桃 / 蜂蜜',
    price: 700,
    roast: '淺焙',
    weight: '100G',
    imageLabel: 'Guji',
    tone: 'light',
  },
  {
    id: 'prod-10',
    name: '哥倫比亞 夏綠蒂波旁',
    category: '淺焙',
    profile: '草莓 / 葡萄 / 可可',
    price: 850,
    roast: '淺焙',
    weight: '100G',
    imageLabel: 'Charlotte',
    tone: 'berry',
  },
  {
    id: 'prod-11',
    name: '豆自己・混搭職人配方',
    category: '中焙',
    profile: '可可 / 榛果 / 奶油',
    price: 380,
    roast: '中焙',
    weight: '半磅',
    imageLabel: 'People Blend',
    tone: 'warm',
  },
  {
    id: 'prod-12',
    name: '肯亞低溫發酵 厭氧批次',
    category: '特殊處理',
    profile: '黑醋栗 / 香料 / 酒香',
    price: 500,
    roast: '淺焙',
    weight: '100G',
    imageLabel: 'Anaerobic',
    tone: 'dark',
  },
];

export const checkoutItems = [
  {
    id: 'checkout-1',
    name: '哥斯大黎加 音樂家系列',
    option: '100G',
    price: 750,
    quantity: 1,
    imageLabel: 'Costa Rica',
    tone: 'light',
  },
  {
    id: 'checkout-2',
    name: '哥倫比亞 天堂莊園 聯盟花藝',
    option: '半磅',
    price: 1100,
    quantity: 1,
    imageLabel: 'Paradise',
    tone: 'warm',
  },
  {
    id: 'checkout-3',
    name: '哥倫比亞 粉紅波旁',
    option: '半磅',
    price: 850,
    quantity: 1,
    imageLabel: 'Pink Bourbon',
    tone: 'berry',
  },
  {
    id: 'checkout-4',
    name: '肯亞 涅里高原 高海拔 AA TOP',
    option: '一磅',
    price: 1400,
    quantity: 1,
    imageLabel: 'Kenya',
    tone: 'light',
  },
  {
    id: 'checkout-5',
    name: '豆自己・混搭職人配方',
    option: '半磅',
    price: 380,
    quantity: 1,
    imageLabel: 'People Blend',
    tone: 'warm',
  },
];

export const productFilters = [
  'ALL',
  'BAP',
  'BSP',
  'BAM',
  'BSM',
  'RAP',
  'RSP',
  'RAM',
  'RSM',
];

export const checkoutShippingOptions = [
  '7-11 店到店',
  '全家 店到店',
  '宅配到府',
];

export const productToolbarGroups = [
  {
    label: 'Origin',
    options: ['全部', '非洲', '洲際', '莊園'],
  },
  {
    label: 'Roast',
    options: ['淺焙', '中焙', '中深焙'],
  },
  {
    label: 'Process',
    options: ['日曬', '水洗', '發酵', '蜜處理'],
  },
];
